### PR TITLE
Settings Window and Layout

### PR DESCRIPTION
**Pull request by Myestery**
/claim #52

Added new Settings window and layout to desktop application

### CODE REVIEW

**Comment by Myestery** [comment]
Screenshot 2024-07-18 at 13 51 54
Screenshot 2024-07-18 at 13 52 13
Screenshot 2024-07-18 at 13 52 23

**Comment by richiemcilroy** [comment]
hey @Myestery, looks great. 

Could you make it look a bit more like the Spacedrive example? a little bit sleeker like this:

Screenshot 2024-07-17 at 14 34 57

looks good so far though, almost there!

**Comment by Myestery** [comment]
> hey @Myestery, looks great.
> 
> Could you make it look a bit more like the Spacedrive example? a little bit sleeker like this:
> 
> Screenshot 2024-07-17 at 14 34 57
> looks good so far though, almost there!

Okay, Should I make it 3 columns or 2 is enough?

**Comment by richiemcilroy** [comment]
2 is great, just like this section here basically

Screenshot 2024-07-18 at 14 03 13

**Comment by ItsEeleeya** [comment]
I'd like to suggest using the default window decorations for that and setting the `titleBarStyle` window option to `"Overlay"` so the window feels more coherent with other ones.

**Comment by Myestery** [comment]
> I'd like to suggest using the default window decorations for that and setting the `titleBarStyle` window option to `"Overlay"` so the window feels more coherent with other ones.

done!

**Comment by Myestery** [comment]
@richiemcilroy I think this is ready to be merged

**Comment by Myestery** [comment]
Just checking in to see the status of the approval for this PR

**Comment by Brendonovich** [comment]
As part of Cap 0.3 a settings page has already been built, thank you for your effort here though!

**Pull request closed without merging**
