### PR TITLE
feat(theme): implement system-wide dark mode toggle

### PR DESCRIPTION
**Pull request by onyedikachi-david**
Fixes: #182 
/claim #182 

- Add dark mode toggle to general settings
- Add text hierarchy with different opacity levels for better readability
- Support system theme preference detection
- Add theme persistence across app restarts

https://github.com/user-attachments/assets/7fa9eaa7-83c4-467d-b45a-90b3a9739071

### CODE REVIEW

**Comment by richiemcilroy** [comment]
hey @onyedikachi-david - looks awesome!

I've just added in the dark mode logo.

Few things I've noticed:
- Blue buttons seem to have black text in dark mode. Should be white text (like normal)
- Previous screenshots in settings text should be white 
- prev-recordings window thumbnails styling doesn't seem correct / consistent
- prev-recordings window screenshot specific thumbnails seem a lot different to video thumbnails
- in-progress-recording window doesn't seem styled correctly (has a white BG and can't see icons for example)

Great work! almost there 😄

**Comment by onyedikachi-david** [comment]
> hey @onyedikachi-david - looks awesome!
> 
> I've just added in the dark mode logo.
> 
> Few things I've noticed:
> 
> * Blue buttons seem to have black text in dark mode. Should be white text (like normal)
> * Previous screenshots in settings text should be white
> * prev-recordings window thumbnails styling doesn't seem correct / consistent
> * prev-recordings window screenshot specific thumbnails seem a lot different to video thumbnails
> * in-progress-recording window doesn't seem styled correctly (has a white BG and can't see icons for example)
> 
> Great work! almost there 😄

@richiemcilroy please confirm the latest commit. pushed some changes. Thank you for the review.

**Comment by richiemcilroy** [comment]
Pushed up a few fixes, good work

**Comment by onyedikachi-david** [comment]
> @richiemcilroy: The claim has been successfully added to reward-all. You can [visit your dashboard](https://console.algora.io) to complete the payment.

Hi, the bounty award is yet to reflect on my dashboard.

**Comment by onyedikachi-david** [comment]
Hi, @richiemcilroy 

Could you please verify at your end, maybe your dashboard, I am yet to receive anything on my end.

algora edit mask

**Comment by onyedikachi-david** [comment]
@richiemcilroy could you please look into this?

**Comment by onyedikachi-david** [comment]
@richiemcilroy

**Comment by onyedikachi-david** [comment]
Hello, @richiemcilroy. Bringing this to your notice again. Could you please look into this. Thanks.

**Comment by onyedikachi-david** [comment]
I really would want to understand what is going on here, why no reply to this?, its really somehow, 3 weeks plus!! and no reply @richiemcilroy 

@zcesur could you please look into this, if it is an Algora  payment issue or something else.

Thank you.

**Comment by richiemcilroy** [comment]
Hey @onyedikachi-david - sorry for missing this. Rewarded and bounty has been paid out. Tipped you extra for the inconvenience, that's my bad!

**Comment by onyedikachi-david** [comment]
> Hey @onyedikachi-david - sorry for missing this. Rewarded and bounty has been paid out. Tipped you extra for the inconvenience, that's my bad!

No, problem sir. Thanks.

**Pull request merged**
