### PR TITLE
(try) Fix camera overlay

### PR DESCRIPTION
**Pull request by ItsEeleeya**
Might be a fix for #25 
- fix: closing overlay now properly sets the selected video to none.

### CODE REVIEW

**Comment by richiemcilroy** [comment]
Looks good @ItsEeleeya thank you.

An easy way to replicate this issue, is once the webcam has loaded, right click the main window and reload. This will then cause the webcam to become disabled and it will no longer work.

Screenshot 2024-07-21 at 17 31 36

**Comment by ItsEeleeya** [comment]
Hey @richiemcilroy, could you please try this again?

From what I saw, after reloading the main window, trying to use `WebviewWindow.getByLabel` would return null even with the window existing. It seems to work when called on the backend so the camera overlay should now properly close and re-initialize.

**Comment by richiemcilroy** [comment]
Seems to work a lot better now @ItsEeleeya!

**Comment by richiemcilroy** [comment]
Thank you :)

**Comment by ItsEeleeya** [comment]
oh, that's great! no problem

By the way, do you also have an issue where no matter what video input you select, the overlay just shows the same input (seems to be the first index)?
I was also going to add an option to preserve the last selected device.

**Comment by richiemcilroy** [comment]
ahh yeah, I see what you mean... hmm, would be good to get that fixed. Feel free to throw up another PR if you manage to

**Comment by richiemcilroy** [comment]
also, I think you need to add a claim to this so I can reward the bounty

**Comment by ItsEeleeya** [comment]
> also, I think you need to add a claim to this so I can reward the bounty

Could you please check your Twitter/X for that? I have messaged you

**Pull request merged**
