### PR TITLE
feat: multiple screen selection

### PR DESCRIPTION
**Pull request by 5war00p**
Contains rust and typescript file changes w.r.to Multi screen selection.

/claim https://github.com/CapSoftware/Cap/issues/114

### CODE REVIEW

**Comment by richiemcilroy** [comment]
Hey @5war00p - tested this out and even though I can see the two different screens in the screen selector - no matter what one I pick, it always records my Macbook screen, not the monitor. Switched between extended mode / screen mirroring. Also, can you change the labels (e.g. Screen 1, Screen 2), to the actual monitor / screen names?

Also, if there's only 1 screen selected, don't allow the option to click select.

**Comment by 5war00p** [comment]
> Hey @5war00p - tested this out and even though I can see the two different screens in the screen selector - no matter what one I pick, it always records my Macbook screen, not the monitor. Switched between extended mode / screen mirroring. Also, can you change the labels (e.g. Screen 1, Screen 2), to the actual monitor / screen names?
> 
> Also, if there's only 1 screen selected, don't allow the option to click select.


I see me change those conditions for name, I don't think if we get names for screens, but will check that up.

Also the IDs of the screens, looks screen IDs not coming accurately.

Will debug it.

**Comment by 5war00p** [comment]
image

I've updated it

**Comment by 5war00p** [comment]
@richiemcilroy Did checked this again? I see there are lot of changes, and I resolved conflicts as well

**Pull request merged**
